server {
    listen 80;
    server_name schedly.test schedly.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name schedly.test schedly.local;

    ssl_certificate /etc/nginx/certs/schedly.test+3.pem;
    ssl_certificate_key /etc/nginx/certs/schedly.test+3-key.pem;

    location / {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}