#!/bin/sh
echo "Formatting code..."
docker-compose exec api composer format

echo "Analyzing code..."
docker-compose exec api composer analyse

echo "Testing code..."
docker-compose exec api composer test

echo "ALL GOOD!"